version: '3'

services:
  mysqlsrv:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_USER: "contact_user"
      MYSQL_PASSWORD: "contactpass"
      MYSQL_DATABASE: "db_contact_book"
    ports:
      - "3306:3306"
    volumes:
      - .:/usr/app/mysql
    networks:
      - mysql-compose-network

networks: 
  mysql-compose-network:
    driver: bridge

    
  app:
    build: .
    container_name: contact_book
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    links:
      - mysqlsrv
    depends_on: 
      - mysqlsrv