version: '3'

services:
  mysqlsrv:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_USER: "contact_user"
      MYSQL_PASSWORD: "contactpass"
      MYSQL_DATABASE: "db_contact_book"
    ports:
      - "3306:3306"
    volumes:
      - .:/usr/app/mysql
    networks:
      - mysql-compose-network
    container_name: mysql-app

  app: ## nome do serviço
    build: . ## localização do dockerfile
    command: npm start ## comando a executar
    ports:
      - "3333:3333" 
    volumes:
      - .:/usr/app
    links:
      - "mysqlsrv"
    depends_on: 
      - "mysqlsrv"
networks: 
  mysql-compose-network:
    driver: bridge

  
    